version: '3.3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'zup_bank_db'
      MYSQL_USER: 'zup_bank_db'
      MYSQL_PASSWORD: 'zup_bank_db'
      MYSQL_ROOT_PASSWORD: 'zup_bank_db'
      SPRING_PROFILES_ACTIVE: 'prod'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  db_test:
    image: mysql
    environment:
      MYSQL_DATABASE: 'zup_bank_db_test'
      MYSQL_USER: 'zup_bank_db_test'
      MYSQL_PASSWORD: 'zup_bank_db_test'
      MYSQL_ROOT_PASSWORD: 'zup_bank_db_test'
      SPRING_PROFILES_ACTIVE: 'test'
    ports:
      - '3307:3306'
    expose:
      - '3307'