version: '3.3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'zup_bank_db'
      MYSQL_USER: 'zup_bank_db'
      MYSQL_PASSWORD: 'zup_bank_db'
      MYSQL_ROOT_PASSWORD: 'zup_bank_db'
      SPRING_PROFILES_ACTIVE: 'prod'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  db_test:
    image: mysql
    environment:
      MYSQL_DATABASE: 'zup_bank_db_test'
      MYSQL_USER: 'zup_bank_db_test'
      MYSQL_PASSWORD: 'zup_bank_db_test'
      MYSQL_ROOT_PASSWORD: 'zup_bank_db_test'
      SPRING_PROFILES_ACTIVE: 'test'
    ports:
      - '3307:3306'
    expose:
      - '3307'
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
#    extra_hosts:
#      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    extra_hosts:
#      - "moby:127.0.0.1"